// @ts-check
/**
 * Agent generator for my-school-BE.
 *
 * Source of truth (hand-written):
 *   .agents/agents.config.json        model tiers, access profiles, service groups, skills list
 *   .agents/specs/<agent>.md          core agent definitions (frontmatter + instructions)
 *   .agents/templates/service-agent.md
 *   .agents/services/<svc>.notes.md   hand-maintained module knowledge
 *   .agents/skills/<skill>/           shared skills (Codex reads this location natively)
 *
 * Generated (never edit by hand):
 *   .agents/catalog/services.json     modules, routes, permissions, Prisma models, dependency graph
 *   .agents/catalog/SERVICES.md       human-readable catalog + Mermaid graph
 *   .claude/agents/*.md               Claude Code subagents
 *   .codex/agents/*.toml              Codex custom agents
 *   .claude/skills/<skill>/           mirror of the shared skills for Claude Code
 *   AGENTS.md roster block            between <!-- agents:roster:start/end --> markers
 *
 * Usage:
 *   node scripts/agents/build.mjs                    write all outputs
 *   node scripts/agents/build.mjs --check            exit 1 if any output is stale (CI / pre-commit)
 *   node scripts/agents/build.mjs --stamp <svc|all>  mark notes as verified against the current code
 *
 * Service agents are built from CODE ONLY (TypeScript AST of src/ + prisma/schema). Documentation
 * is never read. Hand-written notes are stamped with a hash of the module source; when the code
 * changes, the generated agent carries a "verify against code" banner until the notes are re-stamped.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const CHECK = process.argv.includes("--check");
const STAMP = (() => {
    const i = process.argv.indexOf("--stamp");
    return i === -1 ? [] : process.argv.slice(i + 1).filter((a) => !a.startsWith("--"));
})();
const GENERATED_MARKER = "GENERATED by scripts/agents/build.mjs";
const HTTP_DECORATORS = new Set(["Get", "Post", "Put", "Patch", "Delete"]);
const PRISMA_OPS =
    "findUnique|findUniqueOrThrow|findFirst|findFirstOrThrow|findMany|create|createMany|createManyAndReturn|update|updateMany|upsert|delete|deleteMany|count|aggregate|groupBy";
const PRISMA_WRITE_OPS = new Set([
    "create",
    "createMany",
    "createManyAndReturn",
    "update",
    "updateMany",
    "upsert",
    "delete",
    "deleteMany",
]);

const rel = (/** @type {string} */ p) => path.relative(ROOT, p).split(path.sep).join("/");
const abs = (/** @type {string} */ p) => path.join(ROOT, p);
const read = (/** @type {string} */ p) => fs.readFileSync(abs(p), "utf8");
const exists = (/** @type {string} */ p) => fs.existsSync(abs(p));

/** @param {string} dir @returns {string[]} repo-relative file paths, sorted */
function walk(dir) {
    if (!exists(dir)) return [];
    /** @type {string[]} */
    const out = [];
    for (const entry of fs.readdirSync(abs(dir), { withFileTypes: true })) {
        const p = `${dir}/${entry.name}`;
        if (entry.isDirectory()) out.push(...walk(p));
        else out.push(p);
    }
    return out.sort();
}

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

const config = JSON.parse(read(".agents/agents.config.json"));

/** PERMISSION_X -> "X" from app.constants.ts */
function loadConstants() {
    /** @type {Record<string, string>} */
    const map = {};
    const src = read("src/common/constants/app.constants.ts");
    for (const m of src.matchAll(/export const (\w+)\s*=\s*"([^"]*)"/g)) map[m[1]] = m[2];
    return map;
}

/** Model name -> schema file */
function loadPrismaModels() {
    /** @type {Record<string, string>} */
    const models = {};
    for (const file of walk("prisma/schema").filter((f) => f.endsWith(".prisma"))) {
        for (const m of read(file).matchAll(/^model\s+(\w+)\s*\{/gm)) models[m[1]] = file;
    }
    return models;
}

/** @param {string} file */
function parseTs(file) {
    return ts.createSourceFile(file, read(file), ts.ScriptTarget.ES2021, true, ts.ScriptKind.TS);
}

/** @param {ts.Node} node @returns {{ name: string, args: ts.NodeArray<ts.Expression> | [] }[]} */
function decoratorsOf(node) {
    const decs = ts.canHaveDecorators(node) ? (ts.getDecorators(node) ?? []) : [];
    return decs.map((d) => {
        const e = d.expression;
        if (ts.isCallExpression(e)) return { name: e.expression.getText(), args: e.arguments };
        return { name: e.getText(), args: [] };
    });
}

/** @param {ts.Expression | undefined} e */
function stringArg(e) {
    return e && (ts.isStringLiteral(e) || ts.isNoSubstitutionTemplateLiteral(e)) ? e.text : "";
}

/** @param {readonly ts.Expression[]} args @param {Record<string,string>} constants */
function symbolArgs(args, constants) {
    return args.map((a) => {
        const text = a.getText();
        if (constants[text] !== undefined) return constants[text];
        if (ts.isStringLiteral(a)) return a.text;
        return text.includes(".") ? text.split(".").pop() : text;
    });
}

/** @param {ReturnType<typeof decoratorsOf>} decs @param {string} name */
const findDec = (decs, name) => decs.find((d) => d.name === name);

/** @param {string} file @param {Record<string,string>} constants */
function parseControllers(file, constants) {
    const sf = parseTs(file);
    /** @type {any[]} */
    const routes = [];
    sf.forEachChild((node) => {
        if (!ts.isClassDeclaration(node)) return;
        const cdecs = decoratorsOf(node);
        const ctrl = findDec(cdecs, "Controller");
        if (!ctrl) return;
        const base = stringArg(ctrl.args[0]);
        const classRoles = findDec(cdecs, "Roles");
        const classPerms = findDec(cdecs, "Permissions");
        const classPublic = !!findDec(cdecs, "Public");
        for (const member of node.members) {
            if (!ts.isMethodDeclaration(member)) continue;
            const decs = decoratorsOf(member);
            const http = decs.find((d) => HTTP_DECORATORS.has(d.name));
            if (!http) continue;
            const roles = findDec(decs, "Roles") ?? classRoles;
            const perms = findDec(decs, "Permissions") ?? classPerms;
            const op = findDec(decs, "ApiOperation");
            let summary = "";
            if (op && op.args[0] && ts.isObjectLiteralExpression(op.args[0])) {
                for (const prop of op.args[0].properties) {
                    if (ts.isPropertyAssignment(prop) && prop.name.getText() === "summary") {
                        summary = stringArg(prop.initializer);
                    }
                }
            }
            const sub = stringArg(http.args[0]);
            const full = `/${[base, sub].filter(Boolean).join("/")}`.replace(/\/+/g, "/");
            routes.push({
                method: http.name.toUpperCase(),
                path: full,
                handler: member.name.getText(),
                public: classPublic || !!findDec(decs, "Public"),
                roles: roles ? symbolArgs(roles.args, constants) : [],
                permissions: perms ? symbolArgs(perms.args, constants) : [],
                throttled: !!findDec(decs, "Throttle"),
                summary,
                source: `${file}:${sf.getLineAndCharacterOfPosition(member.getStart()).line + 1}`,
            });
        }
    });
    return routes;
}

/** @param {string} file @returns {{ target: string, symbols: string[], typeOnly: boolean }[]} */
function parseModuleImports(file) {
    const sf = parseTs(file);
    /** @type {{ target: string, symbols: string[], typeOnly: boolean }[]} */
    const out = [];
    sf.forEachChild((node) => {
        if (!ts.isImportDeclaration(node)) return;
        const spec = stringArg(/** @type {ts.Expression} */ (node.moduleSpecifier));
        const m = spec.match(/^@modules\/([a-z0-9-]+)/);
        if (!m) return;
        const clause = node.importClause;
        /** @type {string[]} */
        const symbols = [];
        if (clause?.name) symbols.push(clause.name.text);
        if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings)) {
            for (const el of clause.namedBindings.elements) symbols.push(el.name.text);
        }
        out.push({ target: m[1], symbols, typeOnly: !!clause?.isTypeOnly });
    });
    return out;
}

/** @param {string} file */
function parseBarrelExports(file) {
    if (!exists(file)) return [];
    const sf = parseTs(file);
    /** @type {string[]} */
    const names = [];
    sf.forEachChild((node) => {
        if (
            ts.isExportDeclaration(node) &&
            node.exportClause &&
            ts.isNamedExports(node.exportClause)
        ) {
            for (const el of node.exportClause.elements) {
                names.push(
                    node.isTypeOnly || el.isTypeOnly ? `type ${el.name.text}` : el.name.text,
                );
            }
        }
    });
    return names;
}

/** @param {string} src @param {Record<string,string>} models */
function prismaUsage(src, models) {
    const reads = new Set();
    const writes = new Set();
    const re = new RegExp(
        `\\b(?:prismaService|prisma|tx)\\s*\\.\\s*([a-z]\\w*)\\s*\\.\\s*(${PRISMA_OPS})\\b`,
        "g",
    );
    for (const m of src.matchAll(re)) {
        const model = m[1][0].toUpperCase() + m[1].slice(1);
        if (!models[model]) continue;
        (PRISMA_WRITE_OPS.has(m[2]) ? writes : reads).add(model);
    }
    for (const w of writes) reads.delete(w);
    return { reads: [...reads].sort(), writes: [...writes].sort() };
}

/**
 * Methods called on constructor-injected dependencies, e.g. `this.accessPolicy.resolveSubjectAccess(`.
 * @param {string} file
 * @returns {Map<string, Set<string>>} injected type name -> method names
 */
function injectedCalls(file) {
    const sf = parseTs(file);
    /** @type {Map<string, Set<string>>} */
    const calls = new Map();
    sf.forEachChild((node) => {
        if (!ts.isClassDeclaration(node)) return;
        /** @type {Map<string, string>} param name -> type name */
        const params = new Map();
        for (const member of node.members) {
            if (!ts.isConstructorDeclaration(member)) continue;
            for (const p of member.parameters) {
                if (p.type && ts.isTypeReferenceNode(p.type) && ts.isIdentifier(p.name)) {
                    params.set(p.name.text, p.type.typeName.getText());
                }
            }
        }
        if (params.size === 0) return;
        /** @param {ts.Node} n */
        const visit = (n) => {
            if (
                ts.isCallExpression(n) &&
                ts.isPropertyAccessExpression(n.expression) &&
                ts.isPropertyAccessExpression(n.expression.expression) &&
                n.expression.expression.expression.kind === ts.SyntaxKind.ThisKeyword
            ) {
                const type = params.get(n.expression.expression.name.text);
                if (type) {
                    if (!calls.has(type)) calls.set(type, new Set());
                    /** @type {Set<string>} */ (calls.get(type)).add(n.expression.name.text);
                }
            }
            ts.forEachChild(n, visit);
        };
        ts.forEachChild(node, visit);
    });
    return calls;
}

/**
 * Exception types thrown and ERROR_* constants referenced.
 * @param {string[]} files
 */
function errorInventory(files) {
    /** @type {Record<string, number>} */
    const throws = {};
    const constants = new Set();
    for (const file of files) {
        const sf = parseTs(file);
        /** @param {ts.Node} n */
        const visit = (n) => {
            if (
                ts.isThrowStatement(n) &&
                n.expression &&
                ts.isNewExpression(n.expression) &&
                ts.isIdentifier(n.expression.expression)
            ) {
                const type = n.expression.expression.text;
                throws[type] = (throws[type] ?? 0) + 1;
            }
            if (ts.isIdentifier(n) && /^ERROR_[A-Z0-9_]+$/.test(n.text)) constants.add(n.text);
            ts.forEachChild(n, visit);
        };
        visit(sf);
    }
    return {
        throws: Object.fromEntries(Object.entries(throws).sort(([a], [b]) => a.localeCompare(b))),
        errorConstants: [...constants].sort(),
    };
}

/** @param {string[]} files */
function sourceHash(files) {
    const h = crypto.createHash("sha256");
    for (const f of [...files].sort()) {
        h.update(f);
        h.update("\0");
        h.update(read(f).replace(/\r\n/g, "\n"));
        h.update("\0");
    }
    return h.digest("hex").slice(0, 12);
}

/** @param {string} notes @returns {string | null} */
function stampedHash(notes) {
    const m = notes.match(/source-hash:\s*([0-9a-f]{12})/);
    return m ? m[1] : null;
}

/** @param {string} file */
function testStats(file) {
    const src = read(file);
    const cases = [...src.matchAll(/\b(?:it|test)(?:\.each\([^)]*\))?\s*\(\s*["'`]([^"'`]*)/g)].map(
        (m) => m[1],
    );
    return {
        file,
        cases: cases.length,
        stubOnly: cases.length > 0 && cases.every((c) => c === "should be defined"),
    };
}

/** @param {string} notes */
function purposeOf(notes) {
    const m = notes.match(/## Purpose\s*\n([\s\S]*?)(\n## |$)/);
    const text = (m ? m[1] : "").replace(/\s+/g, " ").trim();
    const first = text.split(/(?<=\.)\s/)[0] ?? "";
    return first.replace(/`/g, "");
}

// ---------------------------------------------------------------------------
// Catalog
// ---------------------------------------------------------------------------

function buildCatalog() {
    const constants = loadConstants();
    const models = loadPrismaModels();
    const moduleDirs = fs
        .readdirSync(abs("src/modules"), { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort();

    /** @type {Record<string, string>} module dir -> service name */
    const moduleToService = {};
    for (const dir of moduleDirs) moduleToService[dir] = dir;
    for (const [group, dirs] of Object.entries(config.serviceGroups)) {
        for (const dir of dirs) moduleToService[dir] = group;
    }
    const serviceNames = [...new Set(Object.values(moduleToService))].sort();

    /** @type {Record<string, any>} */
    const services = {};
    for (const name of serviceNames) {
        const dirs = moduleDirs.filter((d) => moduleToService[d] === name);
        const files = dirs
            .flatMap((d) => walk(`src/modules/${d}`))
            .filter((f) => f.endsWith(".ts"));
        const prodFiles = files.filter((f) => !f.endsWith(".spec.ts"));
        const specFiles = files.filter((f) => f.endsWith(".spec.ts"));
        const extraTests = walk("test").filter(
            (f) =>
                /\.(e2e|int)-spec\.ts$/.test(f) && dirs.some((d) => path.basename(f).startsWith(d)),
        );

        /** @type {Record<string, { kind: string, symbols: Set<string>, via: Set<string>, calls: Set<string> }>} */
        const deps = {};
        for (const file of prodFiles) {
            /** @type {Map<string, string>} imported symbol -> target service */
            const symbolTarget = new Map();
            for (const imp of parseModuleImports(file)) {
                const target = moduleToService[imp.target];
                if (!target || target === name) continue;
                deps[target] ??= {
                    kind: "type",
                    symbols: new Set(),
                    via: new Set(),
                    calls: new Set(),
                };
                const d = deps[target];
                imp.symbols.forEach((s) => {
                    d.symbols.add(s);
                    symbolTarget.set(s, target);
                });
                d.via.add(path.basename(file));
                const runtime =
                    !imp.typeOnly &&
                    (file.endsWith(".module.ts") ||
                        imp.symbols.some((s) => /(Service|Module)$/.test(s)));
                if (runtime) d.kind = "runtime";
            }
            for (const [type, methods] of injectedCalls(file)) {
                const target = symbolTarget.get(type);
                if (!target) continue;
                for (const m of methods) deps[target].calls.add(`${type}.${m}`);
            }
        }

        const src = prodFiles.map((f) => read(f)).join("\n");
        const usage = prismaUsage(src, models);
        const serviceFiles = prodFiles.filter((f) => f.endsWith(".service.ts"));
        const schemaFiles = [
            ...new Set([...usage.reads, ...usage.writes].map((m) => models[m])),
        ].sort();

        services[name] = {
            name,
            agent: `svc-${name}`,
            infra: config.infraServices.includes(name),
            modules: dirs,
            paths: dirs.map((d) => `src/modules/${d}/`),
            publicApi: dirs.flatMap((d) => parseBarrelExports(`src/modules/${d}/index.ts`)),
            routes: prodFiles
                .filter((f) => f.endsWith(".controller.ts"))
                .flatMap((f) => parseControllers(f, constants)),
            prisma: {
                reads: usage.reads,
                writes: usage.writes,
                schemaFiles,
            },
            dependsOn: Object.entries(deps)
                .sort(([a], [b]) => a.localeCompare(b))
                .map(([target, d]) => ({
                    service: target,
                    agent: `svc-${target}`,
                    kind: d.kind,
                    symbols: [...d.symbols].sort(),
                    calls: [...d.calls].sort(),
                    via: [...d.via].sort(),
                })),
            usedBy: [],
            errors: errorInventory(prodFiles),
            tests: {
                unit: specFiles.map(testStats),
                other: extraTests.map(testStats),
            },
            serviceFiles,
            serviceLoc: serviceFiles.reduce((n, f) => n + read(f).split("\n").length, 0),
            sourceHash: sourceHash([...prodFiles, ...schemaFiles]),
            notesFile: `.agents/services/${name}.notes.md`,
        };
    }

    for (const svc of Object.values(services)) {
        for (const dep of svc.dependsOn) {
            services[dep.service].usedBy.push({
                service: svc.name,
                agent: svc.agent,
                kind: dep.kind,
                symbols: dep.symbols,
                calls: dep.calls,
            });
        }
    }

    // src/common also consumes module contracts (guards, decorators) — record it as a consumer.
    /** @type {Record<string, Set<string>>} */
    const commonUses = {};
    for (const file of walk("src/common").filter((f) => f.endsWith(".ts"))) {
        for (const imp of parseModuleImports(file)) {
            const target = moduleToService[imp.target];
            if (!target) continue;
            commonUses[target] ??= new Set();
            imp.symbols.forEach((s) => commonUses[target].add(s));
        }
    }
    for (const [target, symbols] of Object.entries(commonUses)) {
        services[target].usedBy.push({
            service: "src/common",
            agent: null,
            kind: "type",
            symbols: [...symbols].sort(),
            calls: [],
        });
    }

    return {
        $comment: `${GENERATED_MARKER} — do not edit. Run \`pnpm agents:build\`.`,
        apiPrefix: "/api/v1",
        services,
    };
}

// ---------------------------------------------------------------------------
// Rendering helpers
// ---------------------------------------------------------------------------

/** @param {string} text */
function parseSpec(text) {
    const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!m) throw new Error("spec is missing frontmatter");
    /** @type {Record<string, string>} */
    const meta = {};
    for (const line of m[1].split("\n")) {
        const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
        if (kv) meta[kv[1]] = kv[2].trim();
    }
    for (const key of ["name", "description", "tier", "access"]) {
        if (!meta[key]) throw new Error(`spec is missing '${key}'`);
    }
    return { meta, body: m[2].trim() + "\n" };
}

/** @param {{ name: string, description: string, tier: string, access: string, body: string, source: string }} a */
function renderClaude(a) {
    const tier = config.modelTiers[a.tier];
    const access = config.access[a.access];
    if (!tier || !access) throw new Error(`${a.name}: unknown tier/access`);
    return [
        "---",
        `name: ${a.name}`,
        `description: ${JSON.stringify(a.description)}`,
        `tools: ${access.claudeTools}`,
        `model: ${tier.claude}`,
        "---",
        "",
        `<!-- ${GENERATED_MARKER} from ${a.source} — do not edit; run \`pnpm agents:build\`. -->`,
        "",
        a.body.trim(),
        "",
    ].join("\n");
}

/** @param {string} s */
function tomlBasic(s) {
    return JSON.stringify(s);
}

/** @param {string} s Multi-line basic string; escapes backslashes and triple quotes. */
function tomlMultiline(s) {
    const escaped = s.replace(/\\/g, "\\\\").replace(/"""/g, '""\\"');
    return `"""\n${escaped}"""`;
}

/** @param {{ name: string, description: string, tier: string, access: string, body: string, source: string }} a */
function renderCodex(a) {
    const tier = config.modelTiers[a.tier];
    const access = config.access[a.access];
    return [
        `# ${GENERATED_MARKER} from ${a.source} — do not edit; run \`pnpm agents:build\`.`,
        `name = ${tomlBasic(a.name)}`,
        `description = ${tomlBasic(a.description)}`,
        `model = ${tomlBasic(tier.codex.model)}`,
        `model_reasoning_effort = ${tomlBasic(tier.codex.reasoning)}`,
        `sandbox_mode = ${tomlBasic(access.codexSandbox)}`,
        `developer_instructions = ${tomlMultiline(a.body.trim() + "\n")}`,
        "",
    ].join("\n");
}

/** @param {string} s */
const cell = (s) => String(s).replace(/\|/g, "\\|");

/** @param {any} svc */
function renderRoutes(svc) {
    if (svc.routes.length === 0) return "_No HTTP routes._";
    const showPerms = svc.routes.some((/** @type {any} */ r) => r.permissions.length > 0);
    const rows = svc.routes.map((/** @type {any} */ r) => {
        const roles = r.public
            ? "**PUBLIC**"
            : r.roles.length
              ? r.roles.join(", ")
              : "any authenticated";
        const perms = showPerms ? ` ${r.permissions.join(", ") || "—"} |` : "";
        const flags = r.throttled ? " (custom throttle)" : "";
        return `| ${r.method} | \`${r.path}\` | \`${r.handler}\` | ${roles} |${perms} ${cell(r.summary)}${flags} |`;
    });
    return [
        `| Method | Path | Handler | Roles |${showPerms ? " Permissions |" : ""} Summary |`,
        `|---|---|---|---|${showPerms ? "---|" : ""}---|`,
        ...rows,
    ].join("\n");
}

/** @param {any[]} links @param {Record<string, any>} services */
function renderLinks(links, services) {
    if (links.length === 0) return "- _None._";
    return links
        .map((l) => {
            const who = l.agent ? `**${l.agent}**` : `\`${l.service}\``;
            const infra = l.agent && services[l.service]?.infra ? " (infra)" : "";
            const kind =
                l.kind === "runtime" ? "runtime (module/service injection)" : "type/contract only";
            const symbols = l.symbols.map((/** @type {string} */ s) => `\`${s}\``).join(", ");
            const calls = l.calls?.length
                ? `. Methods called: ${l.calls.map((/** @type {string} */ c) => `\`${c}()\``).join(", ")}`
                : "";
            return `- ${who}${infra}: ${kind}. Symbols: ${symbols}${calls}`;
        })
        .join("\n");
}

/** @param {any} svc */
function renderFacts(svc) {
    const unitCases = svc.tests.unit.reduce(
        (/** @type {number} */ n, /** @type {any} */ t) => n + t.cases,
        0,
    );
    const allStub =
        svc.tests.unit.length > 0 && svc.tests.unit.every((/** @type {any} */ t) => t.stubOnly);
    const testLine =
        svc.tests.unit.length === 0
            ? "**none**. No spec files exist."
            : `${svc.tests.unit.length} spec file(s), ${unitCases} case(s)${allStub ? '. **Stub-only ("should be defined")**, so real coverage is effectively zero' : ""}`;
    const other = svc.tests.other.length
        ? svc.tests.other.map((/** @type {any} */ t) => `\`${t.file}\``).join(", ")
        : "none";
    const throws = Object.entries(svc.errors.throws)
        .map(([t, n]) => `${t}×${n}`)
        .join(", ");
    const list = (/** @type {string[]} */ xs) =>
        xs.length ? xs.map((x) => `\`${x}\``).join(", ") : "none";
    return [
        `- Paths: ${list(svc.paths)}`,
        `- Service files: ${list(svc.serviceFiles)} (${svc.serviceLoc} lines total)`,
        `- Public API (\`index.ts\`): ${svc.publicApi.length ? list(svc.publicApi) : "_none_"}`,
        `- Prisma models written: ${svc.prisma.writes.length ? svc.prisma.writes.join(", ") : "none"}`,
        `- Prisma models read only: ${svc.prisma.reads.length ? svc.prisma.reads.join(", ") : "none"}`,
        `- Schema files: ${list(svc.prisma.schemaFiles)}`,
        `- Exceptions thrown directly: ${throws || "none"}`,
        `- \`ERROR_*\` constants used: ${list(svc.errors.errorConstants)}`,
        `- Unit tests: ${testLine}`,
        `- Integration/E2E tests: ${other}`,
        `- Source hash: \`${svc.sourceHash}\` (module source + schema files it touches)`,
    ].join("\n");
}

/** @param {any} svc @returns {"fresh" | "stale" | "unstamped" | "missing"} */
function notesState(svc) {
    if (!exists(svc.notesFile)) return "missing";
    const stamped = stampedHash(read(svc.notesFile));
    if (!stamped) return "unstamped";
    return stamped === svc.sourceHash ? "fresh" : "stale";
}

/** @param {any} svc */
function staleBanner(svc) {
    const state = notesState(svc);
    if (state === "fresh" || state === "missing") return "";
    const why =
        state === "stale"
            ? `the module's code or schema changed after these notes were last verified (notes \`${stampedHash(read(svc.notesFile))}\` vs code \`${svc.sourceHash}\`)`
            : "these notes have never been verified against the current code";
    return (
        `> ⚠ **Module knowledge may be stale.** Cause: ${why}. Treat every claim below as a hypothesis, ` +
        `verify it against the code before relying on it, then update the notes and run ` +
        `\`pnpm agents:stamp ${svc.name}\`.\n\n`
    );
}

/** @param {any} svc @param {Record<string, any>} services @param {string} template */
function renderServiceAgent(svc, services, template) {
    const notesPath = svc.notesFile;
    const notesRaw = exists(notesPath)
        ? read(notesPath)
              .replace(/<!--[\s\S]*?-->\s*/g, "")
              .trim()
        : `_No notes yet. Create \`${notesPath}\` from the code (Purpose, Business rules & invariants, Access control notes, Cross-module contracts, Known pitfalls / risks, Test focus), then run \`pnpm agents:stamp ${svc.name}\`._`;
    const notes = staleBanner(svc) + notesRaw.replace(/^## /gm, "### ");
    const purpose = exists(notesPath) ? purposeOf(read(notesPath)) : "";
    const values = {
        agentName: svc.agent,
        service: svc.name,
        paths: svc.paths.join("`, `"),
        testPattern: svc.modules.map((/** @type {string} */ m) => `src/modules/${m}`).join(" "),
        dependsOn: renderLinks(svc.dependsOn, services),
        usedBy: renderLinks(svc.usedBy, services),
        facts: renderFacts(svc),
        routes: renderRoutes(svc),
        notes,
    };
    const body = template.replace(/\{\{(\w+)\}\}/g, (_, k) => {
        if (!(k in values)) throw new Error(`service template: unknown placeholder ${k}`);
        return values[/** @type {keyof typeof values} */ (k)];
    });
    const downstream = svc.usedBy
        .filter((/** @type {any} */ u) => u.agent)
        .map((/** @type {any} */ u) => u.agent);
    const description =
        `Owner/expert for the ${svc.name} module (${svc.paths.join(", ")}). ${purpose} ` +
        `Use for any feature, bug, question, review or test touching this module` +
        (downstream.length ? `; changes to its contract affect ${downstream.join(", ")}.` : ".");
    return {
        name: svc.agent,
        description: description.replace(/\s+/g, " ").trim(),
        tier: config.serviceAgent.tier,
        access: config.serviceAgent.access,
        body,
        source: `.agents/templates/service-agent.md + ${notesPath}`,
    };
}

/** @param {Record<string, any>} services */
function renderServicesMd(services) {
    const list = Object.values(services);
    const edges = [];
    for (const s of list) {
        if (s.infra) continue;
        for (const d of s.dependsOn) {
            if (services[d.service].infra) continue;
            edges.push(
                `    ${s.name.replace(/-/g, "_")} ${d.kind === "runtime" ? "-->" : "-.->"} ${d.service.replace(/-/g, "_")}`,
            );
        }
    }
    const nodes = list
        .filter((s) => !s.infra)
        .map((s) => `    ${s.name.replace(/-/g, "_")}["${s.name}"]`);
    const rows = list.map((s) => {
        const unit = s.tests.unit.reduce(
            (/** @type {number} */ n, /** @type {any} */ t) => n + t.cases,
            0,
        );
        const stub =
            s.tests.unit.length && s.tests.unit.every((/** @type {any} */ t) => t.stubOnly)
                ? " (stub)"
                : "";
        return `| \`${s.agent}\` | ${s.paths.map((/** @type {string} */ p) => `\`${p}\``).join(" ")} | ${s.routes.length} | ${s.dependsOn.map((/** @type {any} */ d) => d.service).join(", ") || "—"} | ${s.usedBy.map((/** @type {any} */ u) => u.service).join(", ") || "—"} | ${unit}${stub} |`;
    });
    const anyPerms = list.some((s) =>
        s.routes.some((/** @type {any} */ r) => r.permissions.length > 0),
    );
    const routeRows = list.flatMap((s) =>
        s.routes.map(
            (/** @type {any} */ r) =>
                `| ${s.name} | ${r.method} | \`${r.path}\` | ${r.public ? "PUBLIC" : r.roles.join(", ") || "any auth"} |${anyPerms ? ` ${r.permissions.join(", ") || "—"} |` : ""}`,
        ),
    );
    const notesRows = list.map(
        (s) => `| \`${s.agent}\` | \`${s.sourceHash}\` | ${notesState(s)} |`,
    );
    return [
        `<!-- ${GENERATED_MARKER} — do not edit; run \`pnpm agents:build\`. -->`,
        "",
        "# Service Catalog",
        "",
        "Everything here is extracted from `src/` and `prisma/schema/` by the TypeScript compiler API. Nothing comes from documentation.",
        "",
        "Solid arrow = runtime dependency (module import / service injection). Dashed = type/contract only.",
        "`platform` (prisma + health) is infrastructure used by every module and is omitted from the graph.",
        "",
        "```mermaid",
        "graph LR",
        ...nodes,
        ...edges,
        "```",
        "",
        "| Agent | Paths | Routes | Depends on | Used by | Unit test cases |",
        "|---|---|---|---|---|---|",
        ...rows,
        "",
        "## Route & access matrix (prefix `/api/v1`)",
        "",
        "Guards only check roles. Per-record access (class or subject teacher, approved access requests, ownership) is enforced inside the services; see each `svc-*` agent.",
        "",
        `| Service | Method | Path | Roles |${anyPerms ? " Permissions |" : ""}`,
        `|---|---|---|---|${anyPerms ? "---|" : ""}`,
        ...routeRows,
        "",
        "## Knowledge freshness",
        "",
        "`fresh` means the notes were verified against exactly this code. `stale`/`unstamped` means verify against the code, update the notes, then run `pnpm agents:stamp <service>`.",
        "",
        "| Agent | Source hash | Notes |",
        "|---|---|---|",
        ...notesRows,
        "",
    ].join("\n");
}

/** @param {{ name: string, description: string }[]} core @param {Record<string, any>} services */
function renderRoster(core, services) {
    return [
        "<!-- agents:roster:start -->",
        `<!-- ${GENERATED_MARKER} — edit .agents/specs/*.md or .agents/services/*.notes.md instead. -->`,
        "",
        "| Agent | Use it for |",
        "|---|---|",
        ...core.map((a) => `| \`${a.name}\` | ${cell(a.description)} |`),
        "",
        "Per-service owner agents (see `.agents/catalog/SERVICES.md` for the dependency graph):",
        "",
        "| Agent | Module(s) | Depends on | Used by |",
        "|---|---|---|---|",
        ...Object.values(services).map(
            (s) =>
                `| \`${s.agent}\` | ${s.paths.map((/** @type {string} */ p) => `\`${p}\``).join(" ")} | ${s.dependsOn.map((/** @type {any} */ d) => d.agent).join(", ") || "—"} | ${s.usedBy.map((/** @type {any} */ u) => u.agent ?? u.service).join(", ") || "—"} |`,
        ),
        "<!-- agents:roster:end -->",
    ].join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
    /** @type {Map<string, string>} repo-relative path -> content */
    const outputs = new Map();

    let catalog = buildCatalog();

    if (STAMP.length) {
        const targets = STAMP.includes("all") ? Object.keys(catalog.services) : STAMP;
        for (const name of targets) {
            const svc = catalog.services[name];
            if (!svc) throw new Error(`--stamp: unknown service '${name}'`);
            if (!exists(svc.notesFile)) throw new Error(`--stamp: ${svc.notesFile} does not exist`);
            const notes = read(svc.notesFile);
            const header = `<!-- source-hash: ${svc.sourceHash} · Hand-maintained module knowledge, derived ONLY from code (src/, prisma/). Embedded into svc-${name} by scripts/agents/build.mjs. After verifying against code, run \`pnpm agents:stamp ${name}\`. -->`;
            const body = notes.replace(/^\s*<!--[\s\S]*?-->\s*/, "");
            fs.writeFileSync(abs(svc.notesFile), `${header}\n\n${body}`);
            console.log(`stamped ${svc.notesFile} @ ${svc.sourceHash}`);
        }
        catalog = buildCatalog();
    }

    outputs.set(".agents/catalog/services.json", JSON.stringify(catalog, null, 4) + "\n");
    outputs.set(".agents/catalog/SERVICES.md", renderServicesMd(catalog.services));

    const core = walk(".agents/specs")
        .filter((f) => f.endsWith(".md"))
        .map((file) => {
            const { meta, body } = parseSpec(read(file));
            if (`${meta.name}.md` !== path.basename(file))
                throw new Error(`${file}: name must match filename`);
            return {
                name: meta.name,
                description: meta.description,
                tier: meta.tier,
                access: meta.access,
                body,
                source: file,
            };
        });

    const template = read(".agents/templates/service-agent.md");
    const svcAgents = Object.values(catalog.services).map((s) =>
        renderServiceAgent(s, catalog.services, template),
    );

    for (const agent of [...core, ...svcAgents]) {
        outputs.set(`.claude/agents/${agent.name}.md`, renderClaude(agent));
        outputs.set(`.codex/agents/${agent.name}.toml`, renderCodex(agent));
    }

    for (const skill of config.skills) {
        const files = walk(`.agents/skills/${skill}`);
        if (files.length === 0)
            throw new Error(
                `skill '${skill}' listed in config but .agents/skills/${skill} is empty`,
            );
        for (const f of files)
            outputs.set(f.replace(/^\.agents\/skills\//, ".claude/skills/"), read(f));
    }

    const agentsMd = read("AGENTS.md");
    const rosterRe = /<!-- agents:roster:start -->[\s\S]*?<!-- agents:roster:end -->/;
    if (!rosterRe.test(agentsMd)) throw new Error("AGENTS.md is missing the agents:roster markers");
    outputs.set("AGENTS.md", agentsMd.replace(rosterRe, renderRoster(core, catalog.services)));

    // Generated files that are no longer produced (e.g. a deleted module) are stale.
    const stale = [...walk(".claude/agents"), ...walk(".codex/agents")].filter(
        (f) => !outputs.has(f) && read(f).includes(GENERATED_MARKER),
    );
    for (const skill of config.skills) {
        for (const f of walk(`.claude/skills/${skill}`)) if (!outputs.has(f)) stale.push(f);
    }

    const changed = [...outputs]
        .filter(([file, content]) => !exists(file) || read(file) !== content)
        .map(([f]) => f);

    const notStamped = Object.values(catalog.services)
        .map((s) => ({ name: s.name, state: notesState(s) }))
        .filter((s) => s.state !== "fresh");
    for (const s of notStamped) {
        console.warn(
            `warning: ${s.name} notes are ${s.state}. Verify them against the code, then run \`pnpm agents:stamp ${s.name}\`.`,
        );
    }
    const failOnNotes = CHECK && config.staleNotes === "fail" && notStamped.length > 0;

    if (CHECK) {
        if (changed.length || stale.length || failOnNotes) {
            console.error(
                "Agent files are out of date. Run `pnpm agents:build` and commit the result.",
            );
            for (const f of changed) console.error(`  changed: ${f}`);
            for (const f of stale) console.error(`  stale:   ${f}`);
            if (failOnNotes)
                console.error("  notes not verified against current code (see warnings)");
            process.exit(1);
        }
        console.log(`Agent files up to date (${outputs.size} files checked).`);
        return;
    }

    for (const f of changed) {
        fs.mkdirSync(path.dirname(abs(f)), { recursive: true });
        fs.writeFileSync(abs(f), /** @type {string} */ (outputs.get(f)));
    }
    for (const f of stale) fs.rmSync(abs(f));
    console.log(
        `Agents built: ${core.length} core + ${svcAgents.length} service agents, ` +
            `${config.skills.length} skills. ${changed.length} file(s) written, ${stale.length} stale removed.`,
    );
}

main();
